### PR TITLE
Favicon added to the site + Copyright year changed

### PR DESCRIPTION
**Pull request by tejas15802**
Favicons for the main page, member page and admin page added + copyright year changed

### CODE REVIEW

**Review by tejas15802 — COMMENTED** [review]
All changes reviewed

**Comment by sanjay-thiyagarajan** [comment]
Good work. Merging with master 👍🏽

**Comment by sanjay-thiyagarajan** [comment]
@tejas15802 I think the favicon needs to be modified. Coz the existing one has  a black background, which should be transparent. @Techipeeyon  might have the transparent version of the logo.

**Comment by sanjay-thiyagarajan** [comment]
You can create a new issue + PR for this task.

**Pull request merged**
