### PR TITLE
Updated Transparent Logo

### PR DESCRIPTION
**Pull request by SSpirate**

### CODE REVIEW

**Comment by tejas15802** [comment]
#51

**Comment by sanjay-thiyagarajan** [comment]
I wonder why the logo hasn't changed much after the merge :) Is it really transparent now ?

**Comment by tejas15802** [comment]
image
image

**Comment by tejas15802** [comment]
what I wanted to say through those pics is, it depends what browser theme the user is using... On light theme it looks just perfect, in dark theme the blue color of the logo seems to getting merged @sanjay-thiyagarajan 
Either the logo's color should be changed to avoid blue mixing with the dark theme

**Comment by sanjay-thiyagarajan** [comment]
Yeah... now it's fine..some issue with my network... I think the logo needs to be reworked to fit into the proper size for favicon

**Comment by tejas15802** [comment]
> Yeah... now it's fine..some issue with my network... I think the logo needs to be reworked to fit into the proper size for favicon

I checked the size its meeting the standards of 32 x 32

**Pull request merged**
