### PR TITLE
Custom 404 and 500 page added

### PR DESCRIPTION
**Pull request by mukesh663**
This is my first pull request. Check once, if everything's correct.

### CODE REVIEW

**Comment by sanjay-thiyagarajan** [comment]
@mukesh663  Great work. Can you share the screenshots of the pages here ?

**Comment by sanjay-thiyagarajan** [comment]
Also, I can see that the PR mentions that 658 files have changed. Kinda weird. Can you summarise your changes in points here ?

**Comment by mukesh663** [comment]
> Also, I can see that the PR mentions that 658 files have changed. Kinda weird. Can you summarise your changes in points here ?

First, when I set debug=false, it showed some internal server error. It was caused due to the path specified for STATIC_ROOT in settings.py. Actually the staticfiles directory didn't exist or for some reason it was not found. So I used 'python manage.py collectstatic' command, which made those 658 file changes.

Some, server errors were caused by the forward slashes that were mentioned in the html pages for including the bootstrap and css. These errors were ignored when debug is set to true.

I have also included the images of custom error pages.
  
404_errorPage
500_errorPage
stackex

**Comment by mukesh663** [comment]
@sanjay-thiyagarajan Can you check now, I have removed the duplicated files.
Only the json file is kept in staticfiles directory and removed other files.

**Comment by sanjay-thiyagarajan** [comment]
> @sanjay-thiyagarajan Can you check now, I have removed the duplicated files.
> Only the json file is kept in staticfiles directory and removed other files.

@mukesh663  yeah this looks good. Try finding an attractive design for both these pages. It need not be the same background provided for working pages.

**Review by sanjay-thiyagarajan — CHANGES_REQUESTED** [review]
Improve the UI of these pages. It might make the visitor bored.

**Comment by sanjay-thiyagarajan** [comment]
@mukesh663  Are you still working on this issue ?

**Pull request closed without merging**
